In [3]:
import sys
import numpy as np
import matplotlib as mplt
import matplotlib.pyplot as plt
from tqdm import tqdm
import pandas as pd
import random
import math
import copy
from typing import Annotated, Any, Callable
from pydantic import BaseModel, Field, WithJsonSchema
import pydantic

import cv2
from PIL import Image

from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple, Union


In [ ]:
%load_ext autoreload
%autoreload 2

import sys
for p in ['../../../../src']:
    if p not in sys.path:
        sys.path.append(p)
        
import spikeml as sml
from spikeml.utils.nb_util import xdisplay, Markup
from spikeml.datasets.dataset import Dataset, SimpleDataset, DataLoader
from spikeml.core.base import Module

from spikeml.core.runner import Context#, run_with_data




The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
N = 16
X = np.random.randn(N, 3)
y = np.random.randint(0, 2, size=N)

dataset = SimpleDataset(X, y)

loader = DataLoader(
    dataset,
    batch_size=6,
    shuffle=True,
    num_workers=0,
    pin_memory=True,
    seed=42
)

for i, (xb, yb) in enumerate(loader):
    print(i, xb.shape, yb.shape)
    print('  ', xb, yb)

dataset = SimpleDataset(X)
loader = DataLoader(
    dataset,
    batch_size=8,
    shuffle=True,
    num_workers=0,
    pin_memory=True,
    seed=42
)

for i, xb in enumerate(loader):
    print(i, xb.shape)
    print('  ', xb)


0 (6, 3) (6,)
   [[ 0.49073378 -0.87583606 -1.08694952]
 [-1.08100381  0.73168422  0.13049582]
 [ 0.43747204 -0.89316438  0.53726661]
 [ 0.28375901  0.69041312  0.36406973]
 [-2.0403358   2.48914935 -0.29610094]
 [ 0.22673447  1.22905641  0.05233452]] [1 1 1 0 1 1]
1 (6, 3) (6,)
   [[ 0.59535354  1.19931331 -1.07447199]
 [ 1.18783372  0.33160833  1.63997533]
 [-2.22233848 -0.2889175   0.07436181]
 [-0.79687641  1.79684472 -0.03532707]
 [ 1.39433023 -0.67513414 -1.00936288]
 [-0.1407085  -0.00891128  1.92075625]] [0 0 0 1 1 1]
2 (4, 3) (4,)
   [[-0.33634567  0.33297762  0.85921679]
 [-2.93241817  0.51113526 -0.79673769]
 [ 0.51331307  1.14295473  0.53460642]
 [-0.52328508 -0.76387712 -0.99983983]] [1 1 1 0]
0 (8, 3)
   [[ 0.49073378 -0.87583606 -1.08694952]
 [-1.08100381  0.73168422  0.13049582]
 [ 0.43747204 -0.89316438  0.53726661]
 [ 0.28375901  0.69041312  0.36406973]
 [-2.0403358   2.48914935 -0.29610094]
 [ 0.22673447  1.22905641  0.05233452]
 [ 0.59535354  1.19931331 -1.07447199]

In [21]:
from typing import Any, Callable, Dict, Optional, Union, List, Tuple

from spikeml.core.runner import Context, run_with_data


In [22]:
SEED=31
dataset = SimpleDataset(X)
loader = DataLoader(dataset, batch_size=10, shuffle=False, num_workers=0, pin_memory=False, seed=SEED)

class TestLayer(Module):
    def propagate(self, s, context):
        print(s)

ref = TestLayer()
run_with_data(ref, loader, 2)


epoch= 0:
idx= 0:
[[ 0.59535354  1.19931331 -1.07447199]
 [-2.93241817  0.51113526 -0.79673769]
 [ 1.39433023 -0.67513414 -1.00936288]
 [ 0.22673447  1.22905641  0.05233452]
 [-0.1407085  -0.00891128  1.92075625]
 [-0.79687641  1.79684472 -0.03532707]
 [ 0.49073378 -0.87583606 -1.08694952]
 [ 1.18783372  0.33160833  1.63997533]
 [-0.52328508 -0.76387712 -0.99983983]
 [-2.0403358   2.48914935 -0.29610094]]
----------
idx= 1:
[[ 0.28375901  0.69041312  0.36406973]
 [ 0.43747204 -0.89316438  0.53726661]
 [-2.22233848 -0.2889175   0.07436181]
 [ 0.51331307  1.14295473  0.53460642]
 [-0.33634567  0.33297762  0.85921679]
 [-1.08100381  0.73168422  0.13049582]]
----------
epoch= 1:
idx= 0:
[[ 0.59535354  1.19931331 -1.07447199]
 [-2.93241817  0.51113526 -0.79673769]
 [ 1.39433023 -0.67513414 -1.00936288]
 [ 0.22673447  1.22905641  0.05233452]
 [-0.1407085  -0.00891128  1.92075625]
 [-0.79687641  1.79684472 -0.03532707]
 [ 0.49073378 -0.87583606 -1.08694952]
 [ 1.18783372  0.33160833  1.639975

{'ref': <__main__.TestLayer at 0x2773793d930>,
 'context': <spikeml.core.runner.Context at 0x2773793d7e0>}