In [1]:
import sys
import numpy as np
import matplotlib as mplt
import matplotlib.pyplot as plt
from tqdm import tqdm
import pandas as pd
import random
import math
import copy
from typing import Any, Annotated, Callable, Dict, List, Optional, Sequence, Tuple, Union


In [ ]:
%load_ext autoreload
%autoreload 2

import sys
for p in ['../../../../src']:
    if p not in sys.path:
        sys.path.append(p)
        
import spikeml as sml
from spikeml.utils.nb_util import xdisplay, Markup
from spikeml.core.signal import signal_dc, signal_pulse, encode1_onehot, encode_onehot, signal_ranges, mean_per_input
from spikeml.core.ngram import build_ngram, ngram_find, ngram_msample, print_ngrams

from spikeml.plot.plot_util import plot_hist, plot_data, plot_lidata, plot_input, plot_xt, plot_mt, plot_spikes, imshow_matrix, imshow_nmatrix
from spikeml.core.params import Params, NNParams, ConnectorParams, SpikeParams, SSensorParams, SNNParams, SSNNParams

from spikeml.core.params import Params, NNParams, ConnectorParams, SpikeParams, SSensorParams, SNNParams, SSNNParams
from spikeml.ui.ipywidgets_ui import ui

from spikeml.core.matrix import matrix_split, normalize_matrix, _mult, cmask, cmask2, matrix_init, matrix_init2
from spikeml.core.monitor import Monitor

from spikeml.core.spikes import pspike, spike
from spikeml.core.base import Component, Module, Fan, Composite, Chain
from spikeml.core.layer import Layer, SimpleLayer, LinearLayer, NormalizeLayer, ThresholdLayer, BinaryThresholdLayer
from spikeml.core.snn import SNN, SSNN, DSSNN
from spikeml.core.sensor import SSensor
from spikeml.core.connector import Connector, LinearConnector, RateConnector, LIConnector, LIConnector2
from spikeml.core.chain import make_snn_chain, make_ssnn_chain, chain_validate

from spikeml.core.snn import ssnn_apply_update
from spikeml.core.feedback import compute_error, xcompute_error, compute_sg, FeedbackAdapter

from spikeml.datasets.dataset import SimpleDataset, DataLoader
from spikeml.core.runner import Context, DataRunner



The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [18]:
N = 6
X = np.random.randn(N, 3)

dataset = SimpleDataset(X)

loader = DataLoader(dataset)

class TestModule(Module):
    def __call__(self, s, context):
        print(s)

runner = DataRunner(TestModule(), loader)

runner.run(options={})



step = 0:
[[-0.10558815 -0.75612134 -0.03915171]]
----------
step = 1:
[[ 1.17594236  0.16253004 -0.92576576]]
----------
step = 2:
[[-0.95694469 -0.40197027  0.01226074]]
----------
step = 3:
[[-0.09586185  2.07378276  1.14474112]]
----------
step = 4:
[[-0.37570678  1.18259743 -0.36825049]]
----------
step = 5:
[[ 0.14482482 -1.61312881 -1.06066144]]
----------


{'ref': <__main__.TestModule at 0x24edab44670>,
 'context': <spikeml.core.runner.Context at 0x24edab46560>}